import { useEffect, useState, type FormEvent } from "react";
import { ArrowRight, Building2, CalendarDays, ClipboardCheck, Download, HardHat, List, MapPin, Pencil, Plus, ShieldCheck } from "lucide-react";
import { makeId, useResources } from "./ResourceContext";
import { downloadCsv, RMBadge, RMDialog, RMEmpty, RMHeader, RMPanel, RMProgress, RMStats, RMTable, RMTabs } from "./ResourceUI";
import type { ResourcePageProps, ResourceProject, Risk } from "./resourceTypes";

const coverage = (project: ResourceProject) => project.points.length ? project.points.filter(p => p.checked).length / project.points.length * 100 : 0;

export default function ProjectsPage({ navigate, focusId, recordView = false }: ResourcePageProps) {
  const { state, change } = useResources(); const [query,setQuery] = useState(""); const [customer,setCustomer] = useState("全部"); const [status,setStatus] = useState("全部"); const [risk,setRisk] = useState("全部");
  const [selectedId,setSelectedId] = useState(recordView ? "" : state.projects[0]?.id || ""); const [detailId,setDetailId] = useState<string | null>(null); const [detailTab,setDetailTab] = useState("overview");
  const [editing,setEditing] = useState<ResourceProject | "new" | null>(null); const [pointProjectId,setPointProjectId] = useState<string | null>(null); const [error,setError] = useState(""); const [layout,setLayout] = useState("list");
  const filtered = state.projects.filter(p => `${p.name} ${p.legacyId || p.id} ${p.manager} ${p.region}`.toLowerCase().includes(query.trim().toLowerCase()) && (customer === "全部" || p.customerId === customer) && (status === "全部" || p.status === status) && (risk === "全部" || p.risk === risk));
  const selected = filtered.find(p => p.id === selectedId) || (recordView ? undefined : filtered[0]); const detail = state.projects.find(p => p.id === detailId);
  const checked = state.projects.reduce((n,p) => n + p.points.filter(point => point.checked).length,0); const totalPoints = state.projects.reduce((n,p) => n + p.points.length,0);
  const publishedTemplates = state.templates.filter(t => t.status === "已发布");
  function reset() { setQuery(""); setCustomer("全部"); setStatus("全部"); setRisk("全部"); }
  useEffect(() => { if (!focusId) return; reset(); if (focusId.startsWith("customer:")) { setCustomer(focusId.slice(9)); setDetailId(null); } else if (state.projects.some(p => p.id === focusId)) { setSelectedId(focusId); setDetailId(focusId); setDetailTab("overview"); } },[focusId]);
  function openDetail(id: string,tab = "overview") { setSelectedId(id); setDetailId(id); setDetailTab(tab); }
  function openEditor(project: ResourceProject | "new") { setError(""); setDetailId(null); setEditing(project); }
  function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const get = (key:string) => String(form.get(key) || "").trim(); const old = editing && editing !== "new" ? editing : null;
    if (["name", "region", "address", "manager", "phone"].some(key => !get(key))) { setError("请补充项目名称、所在地区、现场地址、现场负责人和联系电话，不能仅输入空格。"); return; }
    if (get("endDate") < get("startDate")) { setError("服务结束日期不能早于开始日期。"); return; }
    if (get("nextInspection") && (get("nextInspection") < get("startDate") || get("nextInspection") > get("endDate"))) { setError("下次检查日期应在项目服务期内。"); return; }
    if (!state.customers.some(c => c.id === get("customerId"))) { setError("请选择有效的所属客户。"); return; }
    if (!publishedTemplates.some(t => t.id === get("templateId"))) { setError("请为项目选择已发布的检查模板。"); return; }
    if (state.projects.some(p => p.id !== old?.id && p.name === get("name"))) { setError("项目名称已存在，请使用可区分的名称。"); return; }
    const project: ResourceProject = { ...(old || {}), id: old?.id || makeId("P"), customerId:get("customerId"), name:get("name"), type:get("type"), region:get("region"), address:get("address"), manager:get("manager"), phone:get("phone"), risk:get("risk") as Risk, status:get("status") as ResourceProject["status"], startDate:get("startDate"), endDate:get("endDate"), nextInspection:get("nextInspection"), lastInspection:old?.lastInspection || "", templateId:get("templateId"), hazards:old?.hazards || 0, points:old?.points || [] };
    change(`项目管理 / ${old ? "更新项目与检查方案" : "新建客户关联项目"}`,project.id,s => ({...s,projects:old ? s.projects.map(p => p.id === old.id ? project:p):[project,...s.projects]}));
    setEditing(null);reset();setSelectedId(project.id);openDetail(project.id);
  }
  function addPoint(event:FormEvent<HTMLFormElement>) {
    event.preventDefault();const form=new FormData(event.currentTarget);const name=String(form.get("name") || "").trim();const p=state.projects.find(p=>p.id===pointProjectId);if(!p || !name) {setError("请输入点位名称。");return;}
    if(p.points.some(point=>point.name===name)){setError("此项目已存在同名检查点位。");return;}
    const point={id:makeId("POINT"),name,category:String(form.get("category")),checked:false};
    change("项目管理 / 新增检查点位",p.id,s=>({...s,projects:s.projects.map(project=>project.id===p.id?{...project,points:[...project.points,point]}:project)}));setPointProjectId(null);openDetail(p.id,"points");
  }
  return <section className="rm-page"><RMHeader title="项目管理" description="从服务项目到具体检查点位，统一安排检查方案、现场负责人和设备资源。" actions={<><button className="rm-button" onClick={()=>downloadCsv("项目服务台账.csv",["项目编号","项目名称","所属客户","负责人","风险等级","点位覆盖率","状态","下次检查"],filtered.map(p=>[p.legacyId || p.id,p.name,state.customers.find(c=>c.id===p.customerId)?.name,p.manager,p.risk,`${Math.round(coverage(p))}%`,p.status,p.nextInspection]))}><Download size={16}/>导出台账</button><button className="rm-button rm-primary" onClick={()=>openEditor("new")}><Plus size={16}/>新建项目</button></>}/>
    <RMStats items={[{label:"服务项目",value:state.projects.length,hint:"客户关联与服务范围",onClick:reset},{label:"待复查项目",value:state.projects.filter(p=>p.status==="待复查").length,hint:"优先安排复查计划",tone:"orange",onClick:()=>{reset();setStatus("待复查");}},{label:"高风险项目",value:state.projects.filter(p=>p.risk==="高风险").length,hint:"建议加强专业核查",tone:"red",onClick:()=>{reset();setRisk("高风险");}},{label:"本轮点位覆盖",value:`${totalPoints?Math.round(checked/totalPoints*100):0}%`,hint:`${checked} / ${totalPoints} 个点位已记录检查`}]} />
    <div className="rm-split"><RMPanel title="项目资源台账" subtitle="每个项目均可查看点位、检查方案与绑定设备" actions={<div className="rm-actions"><button className={`rm-button${layout==="list"?" rm-primary":""}`} onClick={()=>setLayout("list")} aria-label="列表视图"><List size={15}/></button><button className={`rm-button${layout==="cards"?" rm-primary":""}`} onClick={()=>setLayout("cards")} aria-label="卡片视图"><Building2 size={15}/></button></div>}>
      <RMTabs value={status} onChange={setStatus} items={["全部","服务中","待复查","筹备中","已归档"].map(s=>({key:s,label:s==="全部"?"全部项目":s}))}/>
      <div className="rm-filters"><label className="rm-field">搜索项目<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="名称 / 编号 / 负责人"/></label><label className="rm-field">所属客户<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="全部">全部客户</option>{state.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="rm-field">风险等级<select value={risk} onChange={e=>setRisk(e.target.value)}>{["全部","高风险","中风险","低风险"].map(r=><option key={r}>{r}</option>)}</select></label><button className="rm-button" onClick={reset}>重置</button></div>
      {layout==="list"?<RMTable rows={filtered} rowKey={p=>p.id} selectedId={selected?.id} onRow={p=>recordView ? openDetail(p.id) : setSelectedId(p.id)} empty={<RMEmpty text="暂无符合条件的项目" onReset={reset}/>} columns={[
        {key:"name",label:"项目 / 客户",width:"33%",render:p=><><button className="rm-link rm-ellipsis" title={p.name} onClick={()=>openDetail(p.id)}>{p.name}</button><span className="rm-table-sub" title={state.customers.find(c=>c.id===p.customerId)?.name}>{state.customers.find(c=>c.id===p.customerId)?.name || "未关联客户"}</span></>},
        {key:"risk",label:"风险",width:"13%",render:p=><RMBadge>{p.risk}</RMBadge>},{key:"coverage",label:"检查覆盖",width:"19%",render:p=><><RMProgress value={coverage(p)}/><span className="rm-table-sub">{p.points.filter(x=>x.checked).length}/{p.points.length} 个点位</span></>},
        {key:"owner",label:"负责人",width:"12%",render:p=>p.manager},{key:"status",label:"状态",width:"13%",render:p=><RMBadge>{p.status}</RMBadge>},{key:"action",label:"操作",width:"10%",render:p=><button className="rm-link" onClick={()=>openDetail(p.id)}>详情</button>}
      ]}/>:<div className="rm-project-grid rm-panel-pad">{filtered.map(p=><article key={p.id} className="rm-project-card"><div className="rm-inline-between"><RMBadge>{p.risk}</RMBadge><span className="rm-muted">{p.type}</span></div><h3>{p.name}</h3><p>{p.region} · {p.manager}</p><RMProgress value={coverage(p)}/><div className="rm-inline-between"><RMBadge>{p.status}</RMBadge><button className="rm-link" onClick={()=>openDetail(p.id)}>项目详情<ArrowRight size={13}/></button></div></article>)}{!filtered.length&&<RMEmpty text="暂无符合条件的项目" onReset={reset}/>}</div>}
      <div className="rm-footer"><span>共 {filtered.length} 个项目 · 点击项目查看资源档案</span><button className="rm-link" onClick={()=>navigate("customers")}>客户管理<ArrowRight size={13}/></button></div>
    </RMPanel>
    <aside className="rm-stack">{!recordView && (selected?<RMPanel title="当前项目概览" actions={<RMBadge>{selected.status}</RMBadge>}><div className="rm-detail-hero"><span className="rm-detail-symbol"><Building2 size={25}/></span><div><h3>{selected.name}</h3><p>{selected.legacyId || selected.id}</p></div></div><dl className="rm-detail-grid"><div className="rm-full"><dt>现场地址</dt><dd>{selected.region} · {selected.address}</dd></div><div><dt>现场负责人</dt><dd>{selected.manager}</dd></div><div><dt>下次检查</dt><dd>{selected.nextInspection || "未安排"}</dd></div><div><dt>检查点位</dt><dd>{selected.points.length} 个</dd></div><div><dt>绑定设备</dt><dd>{state.devices.filter(d=>d.projectId===selected.id).length} 台</dd></div></dl><div className="rm-panel-pad"><button className="rm-button rm-primary" onClick={()=>openDetail(selected.id)}>打开项目档案<ArrowRight size={15}/></button></div></RMPanel>:<RMPanel><RMEmpty text="当前筛选下没有项目"/></RMPanel>)}
      <RMPanel title="近期检查安排" subtitle="按计划日期排序"><div className="rm-list">{[...state.projects].filter(p=>p.nextInspection&&p.status!=="已归档").sort((a,b)=>a.nextInspection.localeCompare(b.nextInspection)).slice(0,3).map(p=><div key={p.id}><div className="rm-inline-between"><span className="rm-muted"><CalendarDays size={13}/> {p.nextInspection}</span><RMBadge>{p.status}</RMBadge></div><button className="rm-link" onClick={()=>openDetail(p.id,"plan")}>{p.name}</button><p>{p.manager} · {state.templates.find(t=>t.id===p.templateId)?.name || "未配置方案"}</p></div>)}</div></RMPanel>
    </aside></div>
    {detail&&<RMDialog drawer={recordView} title={detail.name} onClose={()=>setDetailId(null)} footer={<><button className="rm-button" onClick={()=>openEditor(detail)}><Pencil size={15}/>编辑项目</button><button className="rm-button rm-primary" onClick={()=>navigate("customers",detail.customerId)}>所属客户档案<ArrowRight size={15}/></button></>}>
      <div className="rm-service-strip"><div><strong>{detail.points.length}</strong><span>检查点位</span></div><div><strong>{state.devices.filter(d=>d.projectId===detail.id).length}</strong><span>绑定设备</span></div><div><strong>{Math.round(coverage(detail))}%</strong><span>本轮检查覆盖</span></div></div>
      <RMTabs value={detailTab} onChange={setDetailTab} items={[{key:"overview",label:"项目概览"},{key:"points",label:"检查点位"},{key:"devices",label:"绑定设备"},{key:"plan",label:"方案与计划"}]}/>
      {detailTab==="overview"&&<><dl className="rm-detail-grid">{[["所属客户",state.customers.find(c=>c.id===detail.customerId)?.name || "未关联"],["项目编号",detail.legacyId || detail.id],["项目类型",detail.type],...(recordView ? [["下次检查",detail.nextInspection || "未安排"]] : []),["现场负责人",`${detail.manager} · ${detail.phone}`],["服务周期",`${detail.startDate} 至 ${detail.endDate}`],["详细地址",`${detail.region} · ${detail.address}`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="rm-note"><ShieldCheck size={17}/><span>项目风险：{detail.risk}；待跟进疑似隐患 {detail.hazards} 项（演示汇总）。建议结合现场检查与专家意见开展核查。</span></div></>}
      {detailTab==="points"&&<div className="rm-stack rm-panel-pad"><div className="rm-inline-between"><p className="rm-muted">勾选记录本轮点位覆盖，不代表隐患已通过验收。</p><button className="rm-button" onClick={()=>{setError("");setDetailId(null);setPointProjectId(detail.id);}}><Plus size={14}/>新增点位</button></div><div>{detail.points.map(point=><label key={point.id} className="rm-check-row"><input type="checkbox" checked={point.checked} onChange={e=>{const checked=e.target.checked;change(`项目管理 / ${checked?"记录点位检查":"撤回点位检查记录"}：${point.name}`,detail.id,s=>({...s,projects:s.projects.map(p=>p.id===detail.id?{...p,points:p.points.map(x=>x.id===point.id?{...x,checked}:x)}:p)}));}}/><div><span>{point.name}</span><p>{point.category}</p></div><RMBadge>{point.checked?"已记录检查":"待检查"}</RMBadge></label>)}{!detail.points.length&&<RMEmpty text="暂无检查点位，请先新增点位。"/>}</div></div>}
      {detailTab==="devices"&&<div className="rm-list">{state.devices.filter(d=>d.projectId===detail.id).map(d=><div key={d.id}><div className="rm-inline-between"><button className="rm-link" onClick={()=>navigate("devices",d.id)}><HardHat size={15}/>{d.name}<ArrowRight size={13}/></button><RMBadge>{d.status}</RMBadge></div><p>{d.id} · {d.user} · 固件 {d.firmware}</p></div>)}{!state.devices.some(d=>d.projectId===detail.id)&&<RMEmpty text="暂无绑定设备，可前往设备管理建立关联。"/>}<div><button className="rm-button" onClick={()=>navigate("devices",`project:${detail.id}`)}>管理项目设备<ArrowRight size={14}/></button></div></div>}
      {detailTab==="plan"&&<div className="rm-stack rm-panel-pad"><RMPanel title="检查方案"><div className="rm-panel-pad"><div className="rm-inline-between"><span><ClipboardCheck size={16}/> {state.templates.find(t=>t.id===detail.templateId)?.name || "未配置"}</span><RMBadge>{state.templates.find(t=>t.id===detail.templateId)?.status || "未配置"}</RMBadge></div><p className="rm-muted" style={{marginTop:10}}>版本 V{state.templates.find(t=>t.id===detail.templateId)?.version} · {state.templates.find(t=>t.id===detail.templateId)?.items.length || 0} 项检查要求</p><button className="rm-link" onClick={()=>navigate("templates",detail.templateId)}>查看模板内容<ArrowRight size={13}/></button></div></RMPanel><dl className="rm-detail-grid" style={{padding:0}}><div><dt>最近检查</dt><dd>{detail.lastInspection || "尚无检查记录"}</dd></div><div><dt>下次计划</dt><dd>{detail.nextInspection || "未安排"}</dd></div></dl><button className="rm-button" onClick={()=>openEditor(detail)}>调整方案与计划</button><div className="rm-list">{state.logs.filter(l=>l.target===detail.id).slice(0,5).map(l=><div key={l.id}><span>{l.action}</span><p>{l.time}</p></div>)}</div></div>}
    </RMDialog>}
    {editing&&<RMDialog title={editing==="new"?"新建项目":"编辑项目与检查计划"} onClose={()=>setEditing(null)}><form className="rm-form-grid" onSubmit={save}>{error&&<p className="rm-full rm-text-red" role="alert">{error}</p>}
      <label className="rm-full">项目名称<input name="name" required pattern=".*\S.*" maxLength={60} defaultValue={editing==="new"?"":editing.name}/></label>
      <label className="rm-full">所属客户<select name="customerId" required defaultValue={editing==="new"?(customer==="全部"?state.customers[0]?.id:customer):editing.customerId}>{state.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
      <label>项目类型<select name="type" defaultValue={editing==="new"?"综合楼宇":editing.type}>{["综合楼宇","科技园区","数据中心","商业综合体","工业园区","酒店宾馆","仓储物流"].map(t=><option key={t}>{t}</option>)}</select></label><label>所在地区<input name="region" required pattern=".*\S.*" defaultValue={editing==="new"?"济南市":editing.region}/></label>
      <label className="rm-full">现场地址<input name="address" required pattern=".*\S.*" defaultValue={editing==="new"?"":editing.address}/></label>
      <label>现场负责人<input name="manager" required pattern=".*\S.*" defaultValue={editing==="new"?"":editing.manager}/></label><label>联系电话<input name="phone" required pattern=".*\S.*" defaultValue={editing==="new"?"":editing.phone}/></label>
      <label>服务开始<input name="startDate" required type="date" defaultValue={editing==="new"?new Date().toLocaleDateString("sv-SE"):editing.startDate}/></label><label>服务结束<input name="endDate" required type="date" defaultValue={editing==="new"?"":editing.endDate}/></label>
      <label>项目状态<select name="status" defaultValue={editing==="new"?"筹备中":editing.status}>{["筹备中","服务中","待复查","已归档"].map(s=><option key={s}>{s}</option>)}</select></label><label>风险等级<select name="risk" defaultValue={editing==="new"?"低风险":editing.risk}>{["低风险","中风险","高风险"].map(s=><option key={s}>{s}</option>)}</select></label>
      <label>下次检查<input name="nextInspection" type="date" defaultValue={editing==="new"?"":editing.nextInspection}/></label><label>检查方案（已发布模板）<select name="templateId" required defaultValue={editing==="new"?publishedTemplates[0]?.id:editing.templateId}>{publishedTemplates.map(t=><option value={t.id} key={t.id}>{t.name} · V{t.version}</option>)}</select></label>
      {!publishedTemplates.length&&<div className="rm-note rm-full">暂无已发布模板，请先在检查模板模块完成发布。</div>}
      <div className="rm-form-footer"><button type="button" className="rm-button" onClick={()=>setEditing(null)}>取消</button><button type="submit" className="rm-button rm-primary" disabled={!publishedTemplates.length}>保存项目</button></div>
    </form></RMDialog>}
    {pointProjectId&&<RMDialog title="新增检查点位" onClose={()=>setPointProjectId(null)}><form className="rm-form-grid" onSubmit={addPoint}>{error&&<p role="alert" className="rm-full rm-text-red">{error}</p>}<label className="rm-full">点位名称<input name="name" required pattern=".*\S.*" maxLength={50} placeholder="例如：1号楼B1配电室"/></label><label className="rm-full">检查类别<select name="category"><option>消防安全</option><option>用电安全</option><option>动火临电</option><option>疏散与应急</option></select></label><div className="rm-form-footer"><button className="rm-button" type="button" onClick={()=>setPointProjectId(null)}>取消</button><button className="rm-button rm-primary" type="submit">保存检查点位</button></div></form></RMDialog>}
  </section>;
}
