import React, { useEffect, useRef, useState } from "react";
import { ArrowRight, BookOpen, Database, Download, FileText, Plus, RefreshCw, Search, Settings2, ShieldAlert, Sparkles, Target, Upload, Zap } from "lucide-react";
import { knowledgeCategories, knowledgeDocuments, recentKnowledgeUpdates, type KnowledgeCategory, type KnowledgeDocument } from "../data/modelCenterKnowledgeMock";
import { expertRules as ruleSeed, ruleCategories, type ExpertRule } from "../data/modelCenterExpertRulesMock";
import { getHazardScene, sceneImages } from "../data/demoSceneMedia";
import { hazards, projectNames, tasks } from "./PrototypeFixtures";
import { Button, Drawer, Field, Modal, Pill, PageHeader, SectionCard, MetricCard, Toolbar, downloadText, cx } from "./PrototypeUI";
import "./prototype-intelligence.css";

type Props = { notify: (message: string) => void; navigate?: (path: string, focusId?: string) => void };
type KnowledgeItem = KnowledgeDocument & { docType: string; fileName: string; linkedHazards: string[]; graphNodes: string[] };
type CategoryItem = KnowledgeCategory & { owner: string; description: string };
type RuleItem = ExpertRule & { owner: string };
type RuleVersion = { id: string; version: string; time: string; author: string; summary: string; rule: RuleItem };
const STORE = "safety-prototype-intelligence-v1";
const now = () => new Date().toLocaleString("sv-SE");
const uid = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
const split = (value: string) => value.split(/[,，、\n]/).map((part) => part.trim()).filter(Boolean);
const riskTone = (risk: string) => risk === "高风险" ? "danger" : risk === "中风险" ? "warning" : "success";
const stateTone = (status: string) => ["已更新", "有效", "已发布", "已确认"].includes(status) ? "success" : ["草稿", "待更新", "待复核", "同步中"].includes(status) ? "warning" : "neutral";
const categorySeed: CategoryItem[] = knowledgeCategories.map((item) => ({ ...item, owner: "系统管理员", description: "用于安全检查依据检索、识别校验和整改建议生成。" }));
const documentSeed: KnowledgeItem[] = knowledgeDocuments.map((item) => ({ ...item, docType: "标准规范", fileName: `${item.id}.pdf`, linkedHazards: [], graphNodes: [] }));
const rulesSeed: RuleItem[] = ruleSeed.map((rule) => ({ ...rule, owner: rule.category === "用电安全规则" ? "电气专家组" : "消防安全专家组" }));
const graphOptions = ["配电箱未关闭", "线缆裸露", "电气火灾", "触电风险", "消防通道占用", "灭火器压力不足", "接地异常", "漏电保护缺失"];
const documentTypes = ["标准规范", "典型案例", "检查依据", "整改方案"];
const ruleScenes = ["配电室巡检", "消防设施巡检", "消防通道检查", "动火临电检查", "动火作业检查", "物业巡检"];

function useStored<T,>(key: string, initial: T) {
  const [value, setValue] = useState<T>(() => { try { const saved = sessionStorage.getItem(`${STORE}:${key}`); return saved ? JSON.parse(saved) as T : initial; } catch { return initial; } });
  const current = useRef(value);
  const save = React.useCallback<React.Dispatch<React.SetStateAction<T>>>((update) => {
    const next = typeof update === "function" ? (update as (previous: T) => T)(current.current) : update;
    current.current = next;
    try { sessionStorage.setItem(`${STORE}:${key}`, JSON.stringify(next)); } catch { /* Keep usable state when browser storage is full. */ }
    setValue(next);
  }, [key]);
  return [value, save] as const;
}
function useKnowledgeStore() {
  const [categories, setCategories] = useStored("categories", categorySeed);
  const [documents, setDocuments] = useStored("documents", documentSeed);
  const [updates, setUpdates] = useStored("knowledge-updates", recentKnowledgeUpdates);
  const log = (title: string, category: string, action: string, owner = "系统管理员", documentId = "") => setUpdates((items) => [[now(), title, category, action, owner, documentId], ...items]);
  return { categories, setCategories, documents, setDocuments, updates, setUpdates, log };
}
function Options({ values }: { values: string[] }) { return <>{values.map((value) => <option key={value}>{value}</option>)}</>; }
function Footer({ close, save, saveLabel = "保存" }: { close: () => void; save?: () => void; saveLabel?: string }) { return <div className="modal-foot"><Button variant="secondary" onClick={close}>{save ? "取消" : "关闭"}</Button>{save && <Button onClick={save}>{saveLabel}</Button>}</div>; }
function Details({ rows }: { rows: Array<[string, React.ReactNode]> }) { return <dl className="detail-grid pi-details">{rows.map(([label, value]) => <React.Fragment key={label}><dt>{label}</dt><dd>{value}</dd></React.Fragment>)}</dl>; }
function Empty({ text = "当前筛选条件下没有匹配数据" }: { text?: string }) { return <div className="empty-state">{text}</div>; }
function ChoiceList({ items, values, onChange }: { items: Array<{ id: string; label: string; detail?: string }>; values: string[]; onChange: (next: string[]) => void }) {
  return <div className="pi-choice-list">{items.map((item) => <label key={item.id}><input type="checkbox" checked={values.includes(item.id)} onChange={(event) => onChange(event.target.checked ? [...values, item.id] : values.filter((id) => id !== item.id))} /><span>{item.label}{item.detail && <small>{item.detail}</small>}</span></label>)}</div>;
}
function KnowledgeFields({ value, onChange, categories }: { value: KnowledgeItem; onChange: (value: KnowledgeItem) => void; categories: CategoryItem[] }) {
  const patch = (next: Partial<KnowledgeItem>) => onChange({ ...value, ...next });
  return <div className="form-grid"><Field label="文档名称 *" wide><input value={value.title} onChange={(e) => patch({ title: e.target.value })} /></Field><Field label="所属知识库"><select value={value.category} onChange={(e) => patch({ category: e.target.value })}><Options values={categories.map((item) => item.name)} /></select></Field><Field label="文档类型"><select value={value.docType} onChange={(e) => patch({ docType: e.target.value })}><Options values={documentTypes} /></select></Field><Field label="版本"><input value={value.version} onChange={(e) => patch({ version: e.target.value })} /></Field><Field label="发布单位"><input value={value.publisher} onChange={(e) => patch({ publisher: e.target.value })} /></Field><Field label="更新状态"><select value={value.status} onChange={(e) => patch({ status: e.target.value as KnowledgeItem["status"] })}><Options values={["已更新", "有效", "待更新"]} /></select></Field><Field label="适用场景"><input value={value.scene} onChange={(e) => patch({ scene: e.target.value })} /></Field><Field label="关键词（顿号分隔）" wide><input value={value.keywords.join("、")} onChange={(e) => patch({ keywords: e.target.value.split("、") })} /></Field><Field label="隐患标签（顿号分隔）" wide><input value={value.hazardTags.join("、")} onChange={(e) => patch({ hazardTags: e.target.value.split("、") })} /></Field><Field label="关键条款" wide><textarea value={value.clauses} onChange={(e) => patch({ clauses: e.target.value })} /></Field><Field label="内容摘要" wide><textarea value={value.summary} onChange={(e) => patch({ summary: e.target.value })} /></Field></div>;
}

export function KnowledgeCompletePage({ notify, navigate }: Props) {
  const { categories, setCategories, documents, setDocuments, updates, setUpdates, log } = useKnowledgeStore();
  const [selectedCategory, setSelectedCategory] = useState(categories[0]?.name ?? "");
  const [selectedId, setSelectedId] = useState("");
  const [detailOpen, setDetailOpen] = useState(false);
  const [detailTab, setDetailTab] = useState("文档详情");
  const [filters, setFilters] = useState({ docType: "全部", status: "全部", scene: "全部", keyword: "" });
  const [applied, setApplied] = useState(filters);
  const [modal, setModal] = useState<"create" | "upload" | "preview" | "edit" | "hazard" | "graph" | "delete" | "columns" | "history" | "update" | "category" | null>(null);
  const [moreId, setMoreId] = useState("");
  const [kbDraft, setKbDraft] = useState({ name: "", type: "消防安全", scene: "综合巡检", owner: "系统管理员", description: "用于安全检查依据检索、识别校验和整改建议生成。" });
  const [draft, setDraft] = useState<KnowledgeItem>(documentSeed[0]);
  const [links, setLinks] = useState<string[]>([]);
  const [fileName, setFileName] = useState("");
  const [formError, setFormError] = useState("");
  const [columns, setColumns] = useStored("knowledge-columns", ["所属分类", "关键词", "版本", "更新时间", "状态"]);
  const [updateRow, setUpdateRow] = useState<string[]>([]);
  const syncTimer = useRef<ReturnType<typeof setTimeout>>();
  useEffect(() => () => { if (syncTimer.current) { clearTimeout(syncTimer.current); setCategories((items) => items.map((item) => item.status === "同步中" ? { ...item, status: "已更新" } : item)); } }, [setCategories]);
  const filtered = documents.filter((item) => item.category === selectedCategory && (applied.docType === "全部" || item.docType === applied.docType) && (applied.status === "全部" || item.status === applied.status) && (applied.scene === "全部" || item.scene.includes(applied.scene)) && `${item.title}${item.keywords.join("")}${item.clauses}${item.scene}`.includes(applied.keyword.trim()));
  const selected = documents.find((item) => item.id === selectedId);
  const documentUpdates = selected ? updates.filter(row => row[5] ? row[5] === selected.id : row[1] === selected.title && row[2] === selected.category) : [];
  const showDocument = (doc: KnowledgeItem) => { setSelectedId(doc.id); setDetailTab("文档详情"); setDetailOpen(true); setMoreId(""); };
  const category = categories.find((item) => item.name === selectedCategory);
  const close = () => { setModal(null); setFormError(""); };
  const open = (action: NonNullable<typeof modal>, doc?: KnowledgeItem) => {
    setMoreId(""); setFormError("");
    if (doc) { setSelectedId(doc.id); setSelectedCategory(doc.category); setDraft({ ...doc }); setLinks(action === "hazard" ? doc.linkedHazards : doc.graphNodes); }
    setModal(action);
  };
  const reset = () => { const next = { docType: "全部", status: "全部", scene: "全部", keyword: "" }; setFilters(next); setApplied(next); setSelectedCategory(categories[0]?.name ?? ""); setSelectedId(""); setDetailOpen(false); notify("知识库筛选已重置"); };
  const clearFilters = () => { const next = { docType: "全部", status: "全部", scene: "全部", keyword: "" }; setFilters(next); setApplied(next); };
  const cite = (doc: KnowledgeItem) => { setDocuments((items) => items.map((item) => item.id === doc.id ? { ...item, citations: item.citations + 1 } : item)); setSelectedId(doc.id); log(doc.title, doc.category, "加入检查依据引用，引用次数 +1", "系统管理员", doc.id); notify("已加入检查依据引用"); };
  const addCategory = () => {
    if (!kbDraft.name.trim() || !kbDraft.owner.trim()) return setFormError("请填写知识库名称和负责人。");
    if (categories.some((item) => item.name === kbDraft.name.trim())) return setFormError("知识库名称已存在，请使用其他名称。");
    const next: CategoryItem = { ...kbDraft, id: uid("KB"), name: kbDraft.name.trim(), count: 0, status: "已更新" };
    setCategories((items) => [...items, next]); setSelectedCategory(next.name); setSelectedId(""); clearFilters(); log(next.name, next.name, `新建知识库；负责人：${next.owner}`, next.owner); close(); notify("知识库已新建");
  };
  const startUpload = () => { setFileName(""); setDraft({ ...documentSeed[0], id: uid("KD"), title: "", category: selectedCategory, docType: "标准规范", version: "V1.0", publisher: "", scene: category?.scene ?? "综合巡检", clauses: "", summary: "", keywords: [], hazardTags: [], citations: 0, fileName: "", linkedHazards: [], graphNodes: [] }); open("upload"); };
  const saveDocument = () => {
    if (!draft.title.trim()) return setFormError("请填写文档名称。");
    if (modal === "upload" && !fileName) return setFormError("请选择本地文件或使用内置样例文档。");
    const next = { ...draft, title: draft.title.trim(), keywords: split(draft.keywords.join("、")), hazardTags: split(draft.hazardTags.join("、")), fileName: modal === "upload" ? fileName : draft.fileName, updatedAt: now() };
    setDocuments((items) => modal === "upload" ? [next, ...items] : items.map((item) => item.id === next.id ? next : item));
    if (modal === "upload") setCategories((items) => items.map((item) => item.name === next.category ? { ...item, count: item.count + 1 } : item));
    else if (selected && selected.category !== next.category) setCategories((items) => items.map((item) => item.name === selected.category ? { ...item, count: Math.max(0, item.count - 1) } : item.name === next.category ? { ...item, count: item.count + 1 } : item));
    if (modal !== "upload" && selected) setUpdates(items => items.map(row => !row[5] && row[1] === selected.title && row[2] === selected.category ? [...row.slice(0, 5), selected.id] : row));
    setSelectedCategory(next.category); setSelectedId(next.id); clearFilters(); log(next.title, next.category, modal === "upload" ? `新增文档；文件：${next.fileName}` : "修改文档属性、适用场景及关键条款", "系统管理员", next.id); close(); setDetailOpen(true); setDetailTab("文档详情"); notify("文档已保存，可在列表和详情回读");
  };
  const sync = () => {
    if (!category || category.status === "同步中") return;
    const name = category.name; setCategories((items) => items.map((item) => item.name === name ? { ...item, status: "同步中" } : item));
    syncTimer.current = setTimeout(() => { setCategories((items) => items.map((item) => item.name === name ? { ...item, status: "已更新" } : item)); setDocuments((items) => items.map((item) => item.category === name ? { ...item, status: "已更新", updatedAt: now() } : item)); log(name, name, "本地知识索引同步完成，更新文档状态"); notify(`${name}同步完成`); }, 700);
  };
  const saveLinks = () => { if (!selected) return; const patch = modal === "hazard" ? { linkedHazards: links } : { graphNodes: links }; setDocuments((items) => items.map((item) => item.id === selected.id ? { ...item, ...patch } : item)); log(selected.title, selected.category, `保存${modal === "hazard" ? "隐患" : "图谱"}关联 ${links.length} 项`, "系统管理员", selected.id); close(); notify("关联关系已保存"); };
  const downloadDoc = (doc: KnowledgeItem) => { downloadText(`${doc.id}-知识内容.txt`, `${doc.title}\n版本：${doc.version}\n发布单位：${doc.publisher}\n适用场景：${doc.scene}\n关键条款：${doc.clauses}\n\n${doc.summary}\n\n来源文件：${doc.fileName}\n（本地保存的知识摘要）`); notify("已导出知识内容"); };
  const cells: Record<string, (doc: KnowledgeItem) => React.ReactNode> = { "所属分类": (doc) => doc.category, "关键词": (doc) => doc.keywords.join("、"), "版本": (doc) => doc.version, "更新时间": (doc) => doc.updatedAt, "状态": (doc) => <Pill tone={stateTone(doc.status)}>{doc.status}</Pill> };
  return <div className="page-stack intelligence-complete pi-page"><PageHeader eyebrow="AI PLATFORM / 07" title="知识库" description="沉淀规范条款、检查依据、典型案例和业务场景，支持检索、引用与版本维护。" actions={<><Button variant="secondary" icon={Download} onClick={() => downloadText("知识文档清单.csv", "\uFEFF文档标题,所属分类,版本,状态\n" + documents.map((item) => [item.title, item.category, item.version, item.status].map((value) => `"${value.replace(/"/g, '""')}"`).join(",")).join("\n"), "text/csv;charset=utf-8")}>导出清单</Button><Button icon={Plus} onClick={() => { setKbDraft({ name: "", type: "消防安全", scene: "综合巡检", owner: "系统管理员", description: "用于安全检查依据检索、识别校验和整改建议生成。" }); open("create"); }}>新建知识库</Button></>} />
    <Toolbar><Field label="文档类型"><select value={filters.docType} onChange={(e) => setFilters({ ...filters, docType: e.target.value })}><Options values={["全部", ...documentTypes]} /></select></Field><Field label="更新状态"><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><Options values={["全部", "已更新", "有效", "待更新"]} /></select></Field><Field label="适用场景"><select value={filters.scene} onChange={(e) => setFilters({ ...filters, scene: e.target.value })}><Options values={["全部", "配电", "消防", "巡检", "验收"]} /></select></Field><Field label="关键词"><input value={filters.keyword} onChange={(e) => setFilters({ ...filters, keyword: e.target.value })} placeholder="规范、条款、关键词" onKeyDown={(e) => e.key === "Enter" && setApplied(filters)} /></Field><Button onClick={() => { setApplied(filters); notify("知识库查询完成"); }}>查询</Button><Button variant="secondary" onClick={reset}>重置</Button><Button variant="secondary" icon={RefreshCw} onClick={sync}>{category?.status === "同步中" ? "同步中…" : "同步知识库"}</Button><Button variant="secondary" icon={Upload} onClick={startUpload}>上传文档</Button></Toolbar>
    <div className="metric-grid compact"><MetricCard label="知识库总数" value={`${categories.length}`} detail="覆盖消防与用电安全" icon={BookOpen} tone="blue" /><MetricCard label="文档总数" value={categories.reduce((sum, item) => sum + item.count, 0).toLocaleString()} detail={`当前可操作文档 ${documents.length} 份`} icon={FileText} tone="green" /><MetricCard label="依据引用" value={`${documents.reduce((sum, item) => sum + item.citations, 0)}`} detail="引用次数随操作更新" icon={Search} tone="amber" /><MetricCard label="知识命中率" value="92.3%" detail="关联隐患与整改建议" icon={Target} tone="red" /></div>
    <div className="demo-knowledge-layout"><aside className="section-card knowledge-tree"><div className="section-card-head"><div><div className="eyebrow">KNOWLEDGE CATEGORIES</div><h2>知识库分类</h2></div></div>{categories.map((item) => <button type="button" className={cx("tree-row", selectedCategory === item.name && "active")} key={item.id} onClick={() => { setSelectedCategory(item.name); setSelectedId(""); setDetailOpen(false); }}><span>{item.name}</span><b>{item.count.toLocaleString()}</b><Pill tone={stateTone(item.status)}>{item.status}</Pill></button>)}{category && <div className="pi-category-note"><span>负责人：{category.owner}</span><Button variant="ghost" onClick={() => open("category")}>知识库详情</Button></div>}</aside>
      <section className="section-card knowledge-documents"><div className="section-card-head"><div><div className="eyebrow">DOCUMENT INDEX</div><h2>知识文档 <small>{filtered.length} 条</small></h2></div><div className="pi-list-actions"><Button variant="ghost" onClick={() => open("history")}>更新日志</Button><Button variant="ghost" onClick={() => open("columns")}><Settings2 size={15} />列设置</Button></div></div><div className="table-wrap"><table className="data-table pi-document-table"><colgroup><col style={{ width: 220 }} />{columns.map((column) => <col key={column} style={{ width: column === "更新时间" ? 156 : column === "状态" || column === "版本" ? 80 : 134 }} />)}<col style={{ width: 140 }} /></colgroup><thead><tr><th>文档标题</th>{columns.map((column) => <th key={column}>{column}</th>)}<th>操作</th></tr></thead><tbody>{filtered.map((doc) => <tr key={doc.id} className={detailOpen && selected?.id === doc.id ? "selected" : ""}><td><button type="button" className="pi-record-link pi-cell" title={doc.title} onClick={() => showDocument(doc)}>{doc.title}</button><small>{doc.id}</small></td>{columns.map((column) => <td key={column}><span className="pi-cell">{cells[column]?.(doc)}</span></td>)}<td><div className="row-actions"><Button variant="ghost" onClick={() => showDocument(doc)}>查看</Button><Button variant="ghost" onClick={() => cite(doc)}>引用</Button><Button variant="ghost" onClick={() => setMoreId(moreId === doc.id ? "" : doc.id)}>更多</Button></div>{moreId === doc.id && <div className="pi-row-menu"><button onClick={() => open("edit", doc)}>编辑</button><button onClick={() => open("hazard", doc)}>关联隐患</button><button onClick={() => { downloadDoc(doc); setMoreId(""); }}>下载</button><button onClick={() => open("delete", doc)}>删除</button></div>}</td></tr>)}</tbody></table>{!filtered.length && <Empty />}</div></section>
    </div>
    <div className="pi-record-drawer"><Drawer title="知识文档详情" open={detailOpen && !!selected} onClose={() => { setDetailOpen(false); setSelectedId(""); }}>{selected && <>
      <div className="pi-record-heading"><div><h3>{selected.title}</h3><p>{selected.id} · {selected.category} · {selected.version}</p></div><Pill tone={stateTone(selected.status)}>{selected.status}</Pill></div>
      <nav className="pi-record-tabs" aria-label="文档详情栏目">{["文档详情", "更新记录"].map(tab => <button type="button" key={tab} className={detailTab === tab ? "active" : ""} aria-pressed={detailTab === tab} onClick={() => setDetailTab(tab)}>{tab}{tab === "更新记录" && <span>{documentUpdates.length}</span>}</button>)}</nav>
      <div className="pi-record-body">{detailTab === "文档详情" ? <><Details rows={[["文档名称", selected.title], ["所属分类", selected.category], ["文档类型", selected.docType], ["版本", selected.version], ["发布单位", selected.publisher || "未填写"], ["适用场景", selected.scene], ["关键条款", selected.clauses || "待补充"], ["引用次数", `${selected.citations} 次`], ["更新时间", selected.updatedAt], ["来源文件", selected.fileName], ["关联隐患", selected.linkedHazards.map((id) => hazards.find((item) => item[0] === id)?.[1] ?? id).join("、") || "未关联"], ["图谱节点", selected.graphNodes.join("、") || "未关联"]]} /><p className="detail-copy">{selected.summary}</p><div className="tag-list">{selected.hazardTags.map((tag) => <Pill tone="info" key={tag}>{tag}</Pill>)}</div><div className="detail-actions"><Button variant="secondary" onClick={() => open("edit", selected)}>编辑文档</Button><Button onClick={() => open("preview", selected)}>查看原文</Button><Button variant="secondary" onClick={() => cite(selected)}>加入引用</Button><Button variant="secondary" onClick={() => open("graph", selected)}>关联隐患图谱</Button><Button variant="secondary" onClick={() => open("hazard", selected)}>关联隐患</Button></div></> : <div className="pi-history">{documentUpdates.map((row, index) => <button type="button" key={`${row[0]}-${index}`} onClick={() => { setUpdateRow(row); open("update"); }}><span>{row[3]}</span><small>{row[0]} · {row[4]}</small></button>)}{!documentUpdates.length && <Empty text="该文档暂无更新记录" />}</div>}</div>
    </>}</Drawer></div>

    <Modal title="新建知识库" open={modal === "create"} onClose={close}><div className="form-grid"><Field label="知识库名称 *" wide><input value={kbDraft.name} onChange={(e) => setKbDraft({ ...kbDraft, name: e.target.value })} placeholder="例如：消防控制室巡检要点" /></Field><Field label="类型"><select value={kbDraft.type} onChange={(e) => setKbDraft({ ...kbDraft, type: e.target.value })}><Options values={["消防安全", "用电安全", "物业安全", "园区安全", "作业安全"]} /></select></Field><Field label="适用场景"><select value={kbDraft.scene} onChange={(e) => setKbDraft({ ...kbDraft, scene: e.target.value })}><Options values={["综合巡检", "配电室巡检", "消防巡检", "企业自查", "动火临电"]} /></select></Field><Field label="负责人 *" wide><input value={kbDraft.owner} onChange={(e) => setKbDraft({ ...kbDraft, owner: e.target.value })} /></Field><Field label="描述" wide><textarea value={kbDraft.description} onChange={(e) => setKbDraft({ ...kbDraft, description: e.target.value })} /></Field></div>{formError && <p className="pi-error" role="alert">{formError}</p>}<Footer close={close} save={addCategory} saveLabel="确认新建" /></Modal>
    <Modal title={modal === "upload" ? "上传知识文档" : "编辑文档"} open={modal === "upload" || modal === "edit"} onClose={close} wide>{modal === "upload" && <div className="pi-upload"><Field label="选择本地文件"><input type="file" accept=".pdf,.doc,.docx,.txt,.md" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; setFileName(file.name); setDraft((item) => ({ ...item, title: item.title || file.name.replace(/\.[^.]+$/, "") })); }} /></Field><Button variant="secondary" onClick={() => { setFileName("安全检查补充依据.txt"); setDraft((item) => ({ ...item, title: "安全检查补充依据", summary: "检查配电箱闭锁、消防通道畅通及现场防护措施。", clauses: "现场检查要点：发现异常后记录证据并建议专家复核。" })); }}>使用样例文档</Button><p>已选择：{fileName || "未选择文件"}。文件仅在当前浏览器记录，不传输到服务器。</p></div>}<KnowledgeFields value={draft} onChange={setDraft} categories={categories} />{formError && <p className="pi-error" role="alert">{formError}</p>}<Footer close={close} save={saveDocument} saveLabel={modal === "upload" ? "确认上传" : "保存修改"} /></Modal>
    <Modal title="原文预览" open={modal === "preview"} onClose={close} wide>{selected && <article className="document-preview"><h2>{selected.title}</h2><p>版本：{selected.version} · 发布单位：{selected.publisher || "未填写"}</p><p>{selected.summary}</p><h3>关键条款</h3><p>{selected.clauses || "当前文档尚未录入条款内容。"}</p><p>来源文件：{selected.fileName}；此处展示已录入的条款与内容摘要。</p></article>}<Footer close={close} /></Modal>
    <Modal title={modal === "hazard" ? "关联隐患" : "关联隐患图谱"} open={modal === "hazard" || modal === "graph"} onClose={close} wide><p className="pi-note">当前文档：{selected?.title} · 已选择 {links.length} 项</p><ChoiceList items={modal === "hazard" ? hazards.map((item) => ({ id: item[0], label: item[1], detail: `${item[0]} · ${item[2]} · ${item[5]}` })) : graphOptions.map((label) => ({ id: label, label, detail: "知识依据关联节点" }))} values={links} onChange={setLinks} /><Footer close={close} save={saveLinks} saveLabel="保存关联" /></Modal>
    <Modal title="删除知识文档" open={modal === "delete"} onClose={close}><p>确认从知识库移除“{selected?.title}”？已有引用记录将保留。</p><Footer close={close} saveLabel="确认删除" save={() => { if (!selected) return; setDocuments((items) => items.filter((item) => item.id !== selected.id)); setCategories((items) => items.map((item) => item.name === selected.category ? { ...item, count: Math.max(0, item.count - 1) } : item)); log(selected.title, selected.category, "删除文档", "系统管理员", selected.id); setSelectedId(""); setDetailOpen(false); close(); notify("文档已删除"); }} /></Modal>
    <Modal title="文档列设置" open={modal === "columns"} onClose={close}><p className="pi-note">文档标题和操作列固定显示，其他列可选择。</p><ChoiceList items={Object.keys(cells).map((id) => ({ id, label: id }))} values={columns} onChange={setColumns} /><Footer close={close} /></Modal>
    <Modal title={modal === "history" ? "知识库更新记录" : "更新详情"} open={modal === "history" || modal === "update"} onClose={close} wide>{modal === "history" ? <div className="pi-history">{updates.map((row, index) => <button type="button" key={`${row[0]}-${index}`} onClick={() => { setUpdateRow(row); setModal("update"); }}><span>{row[1]}</span><small>{row[0]} · {row[3]} · {row[4]}</small></button>)}</div> : <Details rows={["更新时间", "文档标题", "所属分类", "更新内容", "操作人"].map((label, index) => [label, updateRow[index]])} />}<Footer close={close} /></Modal>
    <Modal title="知识库详情" open={modal === "category"} onClose={close}>{category && <Details rows={[["知识库名称", category.name], ["类型", category.type], ["适用场景", category.scene], ["负责人", category.owner], ["描述", category.description], ["状态", category.status]]} />}<Footer close={close} />{navigate && <Button variant="ghost" onClick={() => navigate("/model-center/hazard-graph")}>查看隐患图谱</Button>}</Modal>
  </div>;
}

function RuleFields({ value, onChange, disabled = false }: { value: RuleItem; onChange: (value: RuleItem) => void; disabled?: boolean }) {
  const patch = (next: Partial<RuleItem>) => onChange({ ...value, ...next });
  return <><Field label="规则编号"><input value={value.id || "保存后生成"} readOnly /></Field><Field label="规则名称 *"><input disabled={disabled} value={value.name} onChange={(e) => patch({ name: e.target.value })} /></Field><Field label="规则类别"><select disabled={disabled} value={value.category} onChange={(e) => patch({ category: e.target.value })}><Options values={ruleCategories.slice(1).map(([name]) => name)} /></select></Field><Field label="责任组"><input disabled={disabled} value={value.owner} onChange={(e) => patch({ owner: e.target.value })} /></Field><Field label="适用场景"><select disabled={disabled} value={value.scene} onChange={(e) => patch({ scene: e.target.value })}><Options values={Array.from(new Set([...ruleScenes, value.scene]))} /></select></Field><Field label="风险等级"><select disabled={disabled} value={value.risk} onChange={(e) => patch({ risk: e.target.value as RuleItem["risk"] })}><Options values={["高风险", "中风险", "低风险"]} /></select></Field>{value.id && <Field label="状态"><select disabled={disabled} value={value.status} onChange={(e) => patch({ status: e.target.value as RuleItem["status"] })}><Options values={["已发布", "已停用", "草稿"]} /></select></Field>}<Field label="判断要点" wide><textarea disabled={disabled} value={value.points} onChange={(e) => patch({ points: e.target.value })} /></Field><Field label="触发条件 / 判定逻辑 *" wide><textarea disabled={disabled} value={value.condition} onChange={(e) => patch({ condition: e.target.value })} /></Field><Field label="整改建议" wide><textarea disabled={disabled} value={value.suggestion} onChange={(e) => patch({ suggestion: e.target.value })} /></Field><Field label="关联依据" wide><input disabled={disabled} value={value.basis} onChange={(e) => patch({ basis: e.target.value })} /></Field><Field label="隐患标签（顿号分隔）" wide><input disabled={disabled} value={value.tags.join("、")} onChange={(e) => patch({ tags: e.target.value.split("、") })} /></Field><label className="check-line"><input type="checkbox" disabled={disabled} checked={value.needExpert} onChange={(e) => patch({ needExpert: e.target.checked })} />需要专家复核</label><label className="check-line"><input type="checkbox" disabled={disabled} checked={value.keyRectify} onChange={(e) => patch({ keyRectify: e.target.checked })} />建议纳入重点整改</label></>;
}
const initialVersions: RuleVersion[] = rulesSeed.flatMap((rule) => [{ id: `${rule.id}-v23`, version: "V2.3", time: rule.updatedAt, author: rule.owner, summary: "完善触发条件、判断要点及整改建议", rule }, { id: `${rule.id}-v22`, version: "V2.2", time: "2025-05-12 15:18", author: "李工", summary: "录入判断条件，补充现场检查要求", rule: { ...rule, condition: rule.points, suggestion: "建议现场核查并留存证据，确认风险后实施整改。", keyRectify: false, updatedAt: "2025-05-12 15:18" } }]);

export function ExpertRulesCompletePage({ notify }: Props) {
  const [rulesState, setRulesState] = useStored("rules", rulesSeed);
  const [versions, setVersions] = useStored("rule-versions", initialVersions);
  const [selectedId, setSelectedId] = useState("");
  const [recordPanel, setRecordPanel] = useState<"details" | "history" | null>(null);
  const [draft, setDraft] = useState<RuleItem>(rulesState[0] ?? rulesSeed[0]);
  const [filters, setFilters] = useState({ category: "全部规则", risk: "全部", status: "全部", keyword: "", owner: "", from: "", to: "", needExpert: "全部", keyRectify: "全部" });
  const [applied, setApplied] = useState(filters);
  const [editing, setEditing] = useState(false);
  const [advanced, setAdvanced] = useState(false);
  const [checked, setChecked] = useState<string[]>([]);
  const [moreId, setMoreId] = useState("");
  const [modal, setModal] = useState<"create" | "test" | "version" | "compare" | "rollback" | "delete" | "batch" | "basis" | null>(null);
  const [formError, setFormError] = useState("");
  const [activeVersion, setActiveVersion] = useState<RuleVersion | null>(null);
  const [testText, setTestText] = useState("配电箱门未关闭，内部线路裸露，存在触电风险。");
  const [testFile, setTestFile] = useState("");
  const [testResult, setTestResult] = useState<{ hit: boolean; rule: string; risk: string; action: string; time: string } | null>(null);
  const [batchStatus, setBatchStatus] = useState<RuleItem["status"]>("已发布");
  const selected = rulesState.find((rule) => rule.id === selectedId);
  const displayed = editing ? draft : selected;
  const currentVersions = versions.filter((version) => version.rule.id === selectedId);
  const filtered = rulesState.filter((rule) => (applied.category === "全部规则" || rule.category === applied.category) && (applied.risk === "全部" || rule.risk === applied.risk) && (applied.status === "全部" || rule.status === applied.status) && `${rule.id}${rule.name}${rule.condition}${rule.tags.join("")}`.includes(applied.keyword.trim()) && rule.owner.includes(applied.owner.trim()) && (!applied.from || rule.updatedAt.slice(0, 10) >= applied.from) && (!applied.to || rule.updatedAt.slice(0, 10) <= applied.to) && (applied.needExpert === "全部" || rule.needExpert === (applied.needExpert === "是")) && (applied.keyRectify === "全部" || rule.keyRectify === (applied.keyRectify === "是")));
  const close = () => { setModal(null); setFormError(""); };
  const select = (rule: RuleItem, edit = false) => { setSelectedId(rule.id); setDraft({ ...rule }); setEditing(edit); setMoreId(""); setFormError(""); };
  const showRule = (rule: RuleItem, panel: "details" | "history" = "details", edit = false) => { select(rule, edit); setRecordPanel(panel); };
  const closeRecord = () => { setRecordPanel(null); setSelectedId(""); setEditing(false); setFormError(""); };
  const recordVersion = (rule: RuleItem, summary: string) => {
    setVersions((items) => { const previous = items.filter((item) => item.rule.id === rule.id); const version = previous.length ? `V${(Number(previous[0].version.replace("V", "")) + 0.1).toFixed(1)}` : "V1.0"; return [{ id: uid("VERSION"), version, time: now(), author: rule.owner || "系统管理员", summary, rule: { ...rule } }, ...items]; });
  };
  const commit = (rule: RuleItem, summary: string) => { const next = { ...rule, name: rule.name.trim(), tags: split(rule.tags.join("、")), updatedAt: now() }; setRulesState((items) => items.some((item) => item.id === next.id) ? items.map((item) => item.id === next.id ? next : item) : [next, ...items]); recordVersion(next, summary); setSelectedId(next.id); setDraft(next); setEditing(false); notify(summary); };
  const save = (publish = false) => {
    const next = modal === "create" || editing ? draft : selected;
    if (!next) return;
    if (!next.name.trim() || !next.condition.trim()) return setFormError("请填写规则名称和触发条件。");
    commit({ ...next, id: next.id || uid("EX-RULE"), status: publish ? "已发布" : next.status }, publish ? "规则已发布" : modal === "create" ? "规则已新增为草稿" : "规则已保存");
    if (modal === "create") { setRecordPanel("details"); const reset = { ...filters, category: "全部规则", keyword: "", risk: "全部", status: "全部", owner: "", from: "", to: "", needExpert: "全部", keyRectify: "全部" }; setFilters(reset); setApplied(reset); }
    close();
  };
  const open = (action: NonNullable<typeof modal>, rule = selected, version?: RuleVersion) => { if (rule && rule.id !== selectedId) select(rule); else setMoreId(""); setModal(action); if (version) setActiveVersion(version); else if (rule) setActiveVersion(versions.find((item) => item.rule.id === rule.id) ?? null); if (action === "test") { setTestResult(null); setTestFile(""); setTestText(rule?.condition ?? ""); } };
  const create = () => { setDraft({ ...rulesSeed[0], id: "", name: "", condition: "", points: "", suggestion: "", basis: "", tags: [], status: "草稿", updatedAt: now() }); setFormError(""); setModal("create"); };
  const copy = (rule: RuleItem) => { const next = { ...rule, id: uid("EX-RULE"), name: `${rule.name}副本`, status: "草稿" as const }; commit(next, "规则已复制为草稿"); setMoreId(""); const reset = { ...filters, category: "全部规则", status: "全部", keyword: "", risk: "全部", owner: "", from: "", to: "", needExpert: "全部", keyRectify: "全部" }; setFilters(reset); setApplied(reset); };
  const runTest = () => {
    if (!selected) return;
    if (!testText.trim()) return setFormError("请填写测试隐患描述；图片仅记录文件名，命中结果依据描述进行本地匹配。");
    const tokens = Array.from(new Set([...selected.tags, selected.name.replace(/识别规则|检查规则|规则/g, ""), ...selected.condition.split(/[，,。；或]/)])).filter((text) => text.length > 1);
    const subject = /配电箱|线缆|灭火器|消防通道|临时用电|接地线|动火作业/.exec(selected.name)?.[0];
    const negative = /一切正常|全部正常|未发现|无异常|没有隐患/.test(testText);
    const hit = !negative && (tokens.some((token) => testText.includes(token)) || Boolean(subject && testText.includes(subject) && /未|缺|裸露|异常|占用|堵塞|断开|破损|过期/.test(testText)));
    setTestResult({ hit, rule: hit ? selected.name : "无匹配规则", risk: hit ? selected.risk : "未判定", action: hit ? `${selected.suggestion}${selected.needExpert ? " 建议专家复核。" : " 建议人工确认。"}` : "当前描述未命中所选规则，请补充现场描述或选择其他规则。", time: now() }); setFormError(""); notify("本地规则测试已完成");
  };
  const comparisonFields: Array<[string, keyof RuleItem]> = [["规则名称", "name"], ["触发条件", "condition"], ["判断要点", "points"], ["风险等级", "risk"], ["整改建议", "suggestion"], ["关联依据", "basis"], ["责任组", "owner"], ["专家复核", "needExpert"], ["重点整改", "keyRectify"]];
  const showValue = (value: unknown) => typeof value === "boolean" ? value ? "是" : "否" : String(value ?? "");
  return <div className="page-stack intelligence-complete pi-page"><PageHeader eyebrow="AI PLATFORM / 09" title="专家规则库" description="维护风险识别规则、触发条件、依据条款和整改建议，支持测试、版本与批量发布。" actions={<><Button variant="secondary" icon={Download} onClick={() => downloadText("专家规则.json", JSON.stringify(rulesState, null, 2), "application/json")}>导出清单</Button><Button icon={Plus} onClick={create}>新增规则</Button></>} />
    <Toolbar><Field label="规则类别"><select value={filters.category} onChange={(e) => setFilters({ ...filters, category: e.target.value })}><Options values={ruleCategories.map(([name]) => name)} /></select></Field><Field label="风险等级"><select value={filters.risk} onChange={(e) => setFilters({ ...filters, risk: e.target.value })}><Options values={["全部", "高风险", "中风险", "低风险"]} /></select></Field><Field label="状态"><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><Options values={["全部", "已发布", "已停用", "草稿"]} /></select></Field><Field label="关键词"><input value={filters.keyword} onChange={(e) => setFilters({ ...filters, keyword: e.target.value })} placeholder="规则名称、编号或条件" /></Field><Button onClick={() => { setApplied(filters); notify("规则查询完成"); }}>查询</Button><Button variant="secondary" onClick={() => { const next = { category: "全部规则", risk: "全部", status: "全部", keyword: "", owner: "", from: "", to: "", needExpert: "全部", keyRectify: "全部" }; setFilters(next); setApplied(next); }}>重置</Button><Button variant="secondary" onClick={() => open("batch")}>批量操作{checked.length ? ` (${checked.length})` : ""}</Button><Button variant="secondary" onClick={() => setAdvanced(!advanced)}>{advanced ? "收起筛选" : "高级筛选"}</Button></Toolbar>
    {advanced && <Toolbar><Field label="责任组"><input value={filters.owner} onChange={(e) => setFilters({ ...filters, owner: e.target.value })} /></Field><Field label="更新开始日期"><input type="date" value={filters.from} onInput={(e) => setFilters({ ...filters, from: e.currentTarget.value })} onChange={(e) => setFilters({ ...filters, from: e.target.value })} /></Field><Field label="更新结束日期"><input type="date" value={filters.to} min={filters.from} onInput={(e) => setFilters({ ...filters, to: e.currentTarget.value })} onChange={(e) => setFilters({ ...filters, to: e.target.value })} /></Field><Field label="需要专家复核"><select value={filters.needExpert} onChange={(e) => setFilters({ ...filters, needExpert: e.target.value })}><Options values={["全部", "是", "否"]} /></select></Field><Field label="重点整改"><select value={filters.keyRectify} onChange={(e) => setFilters({ ...filters, keyRectify: e.target.value })}><Options values={["全部", "是", "否"]} /></select></Field></Toolbar>}
    <div className="rules-complete-layout"><aside className="section-card rule-tree"><div className="section-card-head"><div><div className="eyebrow">RULE CATEGORIES</div><h2>规则分类</h2></div></div>{ruleCategories.map(([name]) => <button type="button" className={applied.category === name ? "active" : ""} key={name} onClick={() => { setFilters({ ...filters, category: name }); setApplied({ ...applied, category: name }); }}><span>{name}</span><b>{name === "全部规则" ? rulesState.length : rulesState.filter((item) => item.category === name).length}</b></button>)}</aside>
      <section className="section-card rule-list"><div className="section-card-head"><div><div className="eyebrow">EXPERT RULES</div><h2>规则列表 <small>共 {filtered.length} 条</small></h2></div><span className="pi-note">已选 {checked.length} 条</span></div><div className="table-wrap"><table className="data-table pi-rule-table"><colgroup>{[36, 205, 108, 174, 82, 82, 120, 160].map((width, index) => <col key={index} style={{ width }} />)}</colgroup><thead><tr><th><input aria-label="选择当前筛选的全部规则" type="checkbox" checked={filtered.length > 0 && filtered.every((item) => checked.includes(item.id))} onChange={(e) => setChecked(e.target.checked ? Array.from(new Set([...checked, ...filtered.map((item) => item.id)])) : checked.filter((id) => !filtered.some((item) => item.id === id)))} /></th>{["规则名称 / 编号", "规则类别", "命中条件", "风险等级", "状态", "更新时间", "操作"].map((head) => <th key={head}>{head}</th>)}</tr></thead><tbody>{filtered.map((rule) => <tr className={recordPanel && selectedId === rule.id ? "selected" : ""} key={rule.id}><td><input aria-label={`选择${rule.name}`} type="checkbox" checked={checked.includes(rule.id)} onChange={(e) => setChecked(e.target.checked ? [...checked, rule.id] : checked.filter((id) => id !== rule.id))} /></td><td><button type="button" className="pi-record-link pi-cell" title={rule.name} onClick={() => showRule(rule)}>{rule.name}</button><small className="pi-cell" title={rule.id}>{rule.id}</small></td><td>{rule.category}</td><td><span className="pi-cell" title={rule.condition}>{rule.condition}</span></td><td><Pill tone={riskTone(rule.risk)}>{rule.risk}</Pill></td><td><Pill tone={stateTone(rule.status)}>{rule.status}</Pill></td><td><span>{rule.updatedAt.split(" ")[0]}</span><small>{rule.updatedAt.split(" ").slice(1).join(" ")}</small></td><td><div className="row-actions"><Button variant="ghost" onClick={() => showRule(rule)}>查看</Button><Button variant="ghost" onClick={() => showRule(rule, "details", true)}>编辑</Button><Button variant="ghost" onClick={() => commit({ ...rule, status: rule.status === "已发布" ? "已停用" : "已发布" }, rule.status === "已发布" ? "规则已停用" : "规则已启用")}>{rule.status === "已发布" ? "停用" : "启用"}</Button><Button variant="ghost" onClick={() => setMoreId(moreId === rule.id ? "" : rule.id)}>更多</Button></div>{moreId === rule.id && <div className="pi-row-menu"><button onClick={() => copy(rule)}>复制规则</button><button onClick={() => open("test", rule)}>测试规则</button><button onClick={() => showRule(rule, "history")}>版本历史</button><button onClick={() => open("delete", rule)}>删除</button></div>}</td></tr>)}</tbody></table>{!filtered.length && <Empty />}</div></section>
    </div>
    <div className="pi-record-drawer"><Drawer title={editing ? "编辑专家规则" : "专家规则详情"} open={!!recordPanel && !!selected} onClose={closeRecord}>{selected && displayed && <>
      <div className="pi-record-heading"><div><h3>{selected.name}</h3><p>{selected.id} · {selected.category} · {currentVersions[0]?.version || "未保存版本"}</p></div><Pill tone={stateTone(selected.status)}>{selected.status}</Pill></div>
      <nav className="pi-record-tabs" aria-label="规则详情栏目"><button type="button" aria-pressed={recordPanel === "details"} className={recordPanel === "details" ? "active" : ""} onClick={() => setRecordPanel("details")}>规则详情</button><button type="button" disabled={editing} aria-pressed={recordPanel === "history"} className={recordPanel === "history" ? "active" : ""} onClick={() => setRecordPanel("history")}>版本历史 <span>{currentVersions.length}</span></button></nav>
      <div className="pi-record-body">{recordPanel === "details" ? <>
        {editing ? <div className="form-grid pi-rule-editor"><RuleFields value={draft} onChange={setDraft} /></div> : <Details rows={[["规则编号", selected.id], ["规则类别", selected.category], ["责任组", selected.owner], ["适用场景", selected.scene], ["风险等级", <Pill tone={riskTone(selected.risk)}>{selected.risk}</Pill>], ["当前状态", <Pill tone={stateTone(selected.status)}>{selected.status}</Pill>], ["判断要点", selected.points], ["触发条件", selected.condition], ["整改建议", selected.suggestion], ["关联依据", selected.basis], ["隐患标签", selected.tags.join("、")], ["需要专家复核", selected.needExpert ? "是" : "否"], ["建议重点整改", selected.keyRectify ? "是" : "否"], ["更新时间", selected.updatedAt]]} />}
        {formError && !modal && <p className="pi-error" role="alert">{formError}</p>}
        <div className="detail-actions">{editing ? <><Button onClick={() => save()}>保存规则</Button><Button variant="secondary" onClick={() => { setDraft({ ...selected }); setEditing(false); setFormError(""); }}>取消编辑</Button></> : <Button onClick={() => { setDraft({ ...selected }); setEditing(true); }}>编辑规则</Button>}<Button variant="secondary" onClick={() => save(true)}>发布规则</Button>{!editing && <><Button variant="secondary" onClick={() => open("test")}>测试规则</Button><Button variant="secondary" onClick={() => open("basis")}>查看关联依据</Button></>}</div>
      </> : <><SectionCard title="版本历史" eyebrow="VERSION HISTORY"><div className="table-wrap"><table className="data-table pi-version-table" aria-label="当前规则版本历史"><colgroup>{[80, 100, 160, 90, 220, 230].map((width, index) => <col key={index} style={{ width }} />)}</colgroup><thead><tr>{["版本号", "更新人", "更新时间", "状态", "变更摘要", "操作"].map((head) => <th key={head}>{head}</th>)}</tr></thead><tbody>{currentVersions.map((version, index) => <tr key={version.id}><td>{version.version}{index === 0 && <small>当前版本</small>}</td><td>{version.author}</td><td>{version.time}</td><td><Pill tone={stateTone(version.rule.status)}>{version.rule.status}</Pill></td><td><span className="pi-cell" title={version.summary}>{version.summary}</span></td><td><div className="row-actions"><Button variant="ghost" onClick={() => open("compare", selected, version)}>版本对比</Button><Button variant="ghost" disabled={index === 0} onClick={() => open("rollback", selected, version)}>回滚版本</Button><Button variant="ghost" onClick={() => open("version", selected, version)}>查看</Button></div></td></tr>)}</tbody></table>{!currentVersions.length && <Empty text="保存规则后生成版本记录" />}</div></SectionCard>
</>}</div>
    </>}</Drawer></div>
    <Modal title="新增专家规则" open={modal === "create"} onClose={close} wide><div className="form-grid"><RuleFields value={draft} onChange={setDraft} /></div>{formError && <p className="pi-error" role="alert">{formError}</p>}<Footer close={close} save={() => save()} saveLabel="保存草稿" /></Modal>
    <Modal title="规则测试" open={modal === "test"} onClose={close} wide><div className="rule-test"><Pill tone="info">{selected?.name}</Pill><Field label="测试隐患描述 *" wide><textarea value={testText} onChange={(e) => { setTestText(e.target.value); setTestResult(null); }} /></Field><Field label="上传测试图片（仅记录本地文件名）"><input type="file" accept="image/*" onChange={(e) => { setTestFile(e.target.files?.[0]?.name ?? ""); setTestResult(null); }} /></Field>{testFile && <p>已选择图片：{testFile}</p>}<p className="pi-note">本地规则匹配依据描述中的风险关键词，不对图片调用识别接口。</p>{formError && <p className="pi-error" role="alert">{formError}</p>}{testResult && <div className="pi-result" role="status"><Details rows={[["是否命中", testResult.hit ? "命中" : "未命中"], ["命中规则", testResult.rule], ["风险等级", testResult.risk], ["建议动作", testResult.action], ["测试时间", testResult.time]]} /></div>}</div><Footer close={close} save={runTest} saveLabel="开始测试" /></Modal>
    <Modal title={modal === "compare" ? "版本对比" : "版本详情"} open={modal === "version" || modal === "compare"} onClose={close} wide>{activeVersion ? <><Details rows={[["规则名称", activeVersion.rule.name], ["版本", activeVersion.version], ["更新人", activeVersion.author], ["更新时间", activeVersion.time], ["变更说明", activeVersion.summary]]} />{modal === "compare" ? <div className="table-wrap"><table className="data-table pi-compare-table"><thead><tr><th>字段</th><th>{activeVersion.version}</th><th>当前内容</th></tr></thead><tbody>{comparisonFields.map(([label, field]) => <tr className={activeVersion.rule[field] !== selected?.[field] ? "pi-changed" : ""} key={field}><td>{label}</td><td>{showValue(activeVersion.rule[field])}</td><td>{showValue(selected?.[field])}</td></tr>)}</tbody></table></div> : <Details rows={comparisonFields.map(([label, field]) => [label, showValue(activeVersion.rule[field])])} />}</> : <Empty text="该规则尚无保存版本" />}<Footer close={close} /></Modal>
    <Modal title="确认回滚规则版本" open={modal === "rollback"} onClose={close}><p>将“{selected?.name}”恢复为 {activeVersion?.version} 的内容。当前版本会保留，回滚操作将新增一条版本记录。</p>{activeVersion && <Details rows={[["目标触发条件", activeVersion.rule.condition], ["目标风险等级", activeVersion.rule.risk], ["目标整改建议", activeVersion.rule.suggestion]]} />}<Footer close={close} saveLabel="确认回滚" save={() => { if (activeVersion) commit({ ...activeVersion.rule }, `已回滚至 ${activeVersion.version} 内容`); close(); }} /></Modal>
    <Modal title="删除专家规则" open={modal === "delete"} onClose={close}><p>确认删除“{selected?.name}”？历史版本仍保留，其他规则不受影响。</p><Footer close={close} saveLabel="确认删除" save={() => { if (!selected) return; setRulesState((items) => items.filter((item) => item.id !== selected.id)); setChecked((items) => items.filter((id) => id !== selected.id)); setSelectedId(""); setRecordPanel(null); setEditing(false); close(); notify("规则已删除"); }} /></Modal>
    <Modal title="批量操作" open={modal === "batch"} onClose={close}><p className="pi-note">仅更新已勾选的 {checked.length} 条规则。</p><Field label="操作后状态"><select value={batchStatus} onChange={(e) => setBatchStatus(e.target.value as RuleItem["status"])}><Options values={["已发布", "已停用", "草稿"]} /></select></Field><div className="pi-history">{rulesState.filter((item) => checked.includes(item.id)).map((item) => <p key={item.id}>{item.name}</p>)}</div>{formError && <p className="pi-error" role="alert">{formError}</p>}<Footer close={close} saveLabel="确认批量更新" save={() => { if (!checked.length) return setFormError("请先在规则列表勾选需要操作的规则。"); const targets = rulesState.filter((item) => checked.includes(item.id)).map((item) => ({ ...item, status: batchStatus, updatedAt: now() })); setRulesState((items) => items.map((item) => targets.find((target) => target.id === item.id) ?? item)); targets.forEach((item) => recordVersion(item, `批量设置为${batchStatus}`)); setEditing(false); close(); notify(`已更新 ${targets.length} 条规则`); }} /></Modal>
    <Modal title="关联依据" open={modal === "basis"} onClose={close}><Details rows={[["规则", selected?.name], ["依据条款", selected?.basis || "尚未录入关联依据"], ["判断要点", selected?.points], ["适用场景", selected?.scene], ["建议动作", selected?.suggestion]]} /><Footer close={close} /></Modal>
  </div>;
}

type AnalysisRecord = { id: string; name: string; taskId: string; taskName: string; project: string; model: string; type: string; input: string; output: string; confidence: string; duration: string; status: string; time: string; image: string; description: string; risk: string; measure: string; confirmation: string; basisIds: string[]; hazardId?: string; suggestionGenerated?: boolean };
const recordSeed: AnalysisRecord[] = [
  { id: "AI-0001", name: "配电室巡检 · 001", taskId: tasks[0][0], taskName: tasks[0][1], project: tasks[0][3], model: "消防用电视觉模型", type: "图片识别", input: "配电室现场图片", output: "配电箱门未关闭", confidence: "96.8%", duration: "1.7s", status: "待复核", time: "2025-05-16 15:29:00", image: sceneImages.electricalPanelOpen, description: "配电箱门未关闭，内部接线区域可接近，存在触电或短路风险，建议现场核查。", risk: "高风险", measure: "立即关闭配电箱门并上锁，核查线缆绝缘、箱内防护与接地状态，留存整改前后照片。", confirmation: "待人工确认", basisIds: ["KD-0001", "KD-0004"] },
  { id: "AI-0002", name: "消防通道巡检 · 015", taskId: tasks[2][0], taskName: tasks[2][1], project: tasks[2][3], model: "消防设施识别模型", type: "图片识别", input: "消防通道现场图片", output: "消防通道堆放杂物", confidence: "94.2%", duration: "2.1s", status: "已确认", time: "2025-05-16 14:50:00", image: sceneImages.fireCorridorBlocked, description: "通道可见堆放物，建议核查疏散宽度与通行条件。", risk: "高风险", measure: "清理通道堆放物，恢复疏散宽度，补拍同角度照片复核。", confirmation: "建议整改", basisIds: ["KD-0002"] },
  { id: "AI-0003", name: "动火临电检查 · 008", taskId: tasks[3][0], taskName: tasks[3][1], project: tasks[3][3], model: "临电风险模型", type: "图片识别", input: "动火临电现场图片", output: "临时电源箱防护待核查", confidence: "91.5%", duration: "1.4s", status: "待复核", time: "2025-05-16 13:35:00", image: sceneImages.temporaryPower, description: "临时用电配电箱防护与漏保配置需要现场确认。", risk: "中风险", measure: "建议检查漏电保护、接地及箱体防护措施，整改完成后复查。", confirmation: "待人工确认", basisIds: ["KD-0004"] }
];

export function IntelligencePage({ type, notify, navigate }: Props & { type: string }) {
  if (type === "knowledge") return <KnowledgeCompletePage notify={notify} navigate={navigate} />;
  if (type === "expertRules") return <ExpertRulesCompletePage notify={notify} navigate={navigate} />;
  return <ModelCenterPage notify={notify} navigate={navigate} />;
}

function ModelCenterPage({ notify, navigate }: Props) {
  const { categories, setCategories, documents, setDocuments, log } = useKnowledgeStore();
  const [rules, setRules] = useStored("rules", rulesSeed);
  const [versions, setVersions] = useStored("rule-versions", initialVersions);
  const [records, setRecords] = useStored("records", recordSeed);
  const [selectedId, setSelectedId] = useState(records[0]?.id ?? "");
  const [query, setQuery] = useState("");
  const [appliedQuery, setAppliedQuery] = useState("");
  const [modal, setModal] = useState<"analysis" | "record" | "basis" | "knowledge" | "newKnowledge" | "rules" | "newRule" | "messages" | "register" | null>(null);
  const [basisKeyword, setBasisKeyword] = useState("配电");
  const [newKnowledge, setNewKnowledge] = useState({ name: "消防控制室巡检要点", category: categories[0]?.name ?? "", scene: "配电室巡检、消防设施检查、物业安全检查", owner: "系统管理员", description: "用于检查依据检索和整改建议生成。" });
  const [newRule, setNewRule] = useState({ name: "配电箱闭锁检查规则", owner: "电气专家组", condition: "当现场图片识别到配电箱门未关闭时，匹配高风险疑似隐患并建议立即闭锁处理。" });
  const [analysis, setAnalysis] = useState({ name: "配电室现场分析", taskId: tasks[0][0], project: tasks[0][3], model: "消防用电视觉模型", type: "图片识别", input: "", description: "配电箱门未关闭，建议核查。", image: sceneImages.electricalPanelOpen });
  const [confirmation, setConfirmation] = useState("建议整改");
  const [opinion, setOpinion] = useState("");
  const [formError, setFormError] = useState("");
  const [registerDraft, setRegisterDraft] = useState({ title: "", risk: "高风险", description: "", measure: "" });
  const selected = records.find((record) => record.id === selectedId);
  const filtered = records.filter((record) => `${record.name}${record.project}${record.type}${record.output}${record.confirmation}`.includes(appliedQuery.trim()));
  const basis = documents.filter((doc) => `${doc.title}${doc.category}${doc.keywords.join("")}${doc.hazardTags.join("")}${doc.clauses}`.includes(basisKeyword.trim()));
  const close = () => { setModal(null); setFormError(""); };
  const openRecord = (record: AnalysisRecord) => { setSelectedId(record.id); setConfirmation(["建议整改", "建议专家复核", "确认无隐患"].find((item) => record.confirmation.startsWith(item)) ?? "建议整改"); setOpinion(record.confirmation.includes("：") ? record.confirmation.split("：").slice(1).join("：") : ""); setModal("record"); setFormError(""); };
  const patchRecord = (patch: Partial<AnalysisRecord>) => { if (selected) setRecords((items) => items.map((item) => item.id === selected.id ? { ...item, ...patch } : item)); };
  const startAnalysis = () => {
    if (!analysis.name.trim() || !analysis.input.trim() || !analysis.description.trim()) return setFormError("请填写分析名称、输入材料和现场描述，可选择本地文件或内置样例。");
    const source = analysis.model === "消防设施识别模型" ? recordSeed[1] : analysis.model === "临电风险模型" ? recordSeed[2] : recordSeed[0];
    const task = tasks.find((item) => item[0] === analysis.taskId);
    const next: AnalysisRecord = { ...source, ...analysis, id: uid("AI"), taskName: task?.[1] ?? "独立分析", name: analysis.name.trim(), status: "待复核", confirmation: "待人工确认", time: now(), image: analysis.image || source.image, basisIds: source.basisIds.slice(), duration: "1.8s", hazardId: undefined, suggestionGenerated: false };
    setRecords((items) => [next, ...items]); setAppliedQuery(""); setQuery(""); openRecord(next); notify("本地分析结果已生成，等待人工复核");
  };
  const addKnowledge = () => {
    if (!newKnowledge.name.trim() || !newKnowledge.owner.trim()) return setFormError("请填写知识名称和负责人。");
    const category = newKnowledge.category || categories[0]?.name;
    const next: KnowledgeItem = { ...documentSeed[0], id: uid("KD"), title: newKnowledge.name.trim(), category, scene: newKnowledge.scene, publisher: newKnowledge.owner, summary: newKnowledge.description, docType: "检查依据", version: "V1.0", citations: 0, updatedAt: now(), clauses: newKnowledge.description, keywords: split(newKnowledge.name), hazardTags: [], fileName: "手工录入", linkedHazards: [], graphNodes: [] };
    setDocuments((items) => [next, ...items]); setCategories((items) => items.map((item) => item.name === category ? { ...item, count: item.count + 1 } : item)); log(next.title, category, "中台新增知识", newKnowledge.owner); setModal("knowledge"); notify("知识已保存到知识库");
  };
  const addRule = () => {
    if (!newRule.name.trim() || !newRule.owner.trim() || !newRule.condition.trim()) return setFormError("请填写规则名称、责任组和判定逻辑。");
    const next: RuleItem = { ...rulesSeed[0], id: uid("EX-RULE"), name: newRule.name.trim(), owner: newRule.owner, condition: newRule.condition, points: newRule.condition, status: "草稿", updatedAt: now() };
    setRules((items) => [next, ...items]); setVersions([{ id: uid("VERSION"), version: "V1.0", time: now(), author: next.owner, summary: "中台新增规则草稿", rule: next }, ...versions]); setModal("rules"); notify("专家规则草稿已保存");
  };
  const register = () => {
    if (!selected || !registerDraft.title.trim() || !registerDraft.description.trim() || !registerDraft.measure.trim()) return setFormError("请填写隐患名称、问题描述和整改措施。");
    const id = selected.hazardId ?? uid("HD-AI");
    const handoff = { id, title: registerDraft.title.trim(), project: selected.project, taskId: selected.taskId, taskName: selected.taskName, source: "AI识别", risk: registerDraft.risk, image: selected.image, description: registerDraft.description, measure: registerDraft.measure, foundTime: selected.time };
    try { sessionStorage.setItem("safety-prototype-hazard-handoff-v1", JSON.stringify(handoff)); } catch { return setFormError("浏览器暂不能保存移交记录，请释放本地存储后重试。"); }
    patchRecord({ hazardId: id }); close(); notify("隐患信息已移交登记页面"); navigate?.("/hazards", id);
  };
  return <div className="page-stack pi-page"><PageHeader eyebrow="AI PLATFORM / 06" title="大模型中台" description="管理模型、识别队列、推理结果与人工复核链路。" actions={<><Button variant="secondary" icon={Download} onClick={() => downloadText("AI处理记录.json", JSON.stringify(records, null, 2), "application/json")}>导出数据</Button><Button icon={Plus} onClick={() => { setModal("analysis"); setFormError(""); }}>启动分析</Button></>} />
    <div className="metric-grid"><MetricCard label="在线模型" value="06" detail="4 个视觉 · 2 个文本" icon={Sparkles} tone="blue" /><MetricCard label="今日推理" value={(1284 + records.length - recordSeed.length).toLocaleString()} detail="平均耗时 1.8 秒" icon={Zap} tone="green" /><MetricCard label="待人工复核" value={`${records.filter((item) => item.status === "待复核").length}`} detail="当前队列待复核记录" icon={ShieldAlert} tone="red" /><MetricCard label="知识命中率" value="92.6%" detail="较上周提升 4.2%" icon={Database} tone="amber" /></div>
    <div className="pipeline-card"><div className="pipeline-head"><div><div className="eyebrow">MODEL PIPELINE</div><h2>识别处理链路</h2></div><Pill tone="success">运行正常</Pill></div><div className="pipeline-steps">{[["01", "现场采集", "36 路在线"], ["02", "视觉识别", `${records.length} 条本地记录`], ["03", "规则匹配", `规则 ${rules.length} 条`], ["04", "风险评估", `${records.filter((item) => item.status === "待复核").length} 条需复核`], ["05", "闭环分派", `${records.filter((item) => item.hazardId).length} 条已移交`]].map((step, index) => <React.Fragment key={step[0]}><div className={cx("pipeline-step", index === 3 && "active")}><span>{step[0]}</span><strong>{step[1]}</strong><small>{step[2]}</small></div>{index < 4 && <ArrowRight className="pipeline-arrow" size={17} />}</React.Fragment>)}</div></div>
    <Toolbar><label className="search-field"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索任务、项目、识别结果" onKeyDown={(e) => e.key === "Enter" && setAppliedQuery(query)} /></label><Button onClick={() => setAppliedQuery(query)}>查询</Button><Button variant="secondary" onClick={() => { setQuery(""); setAppliedQuery(""); }}>重置</Button><Button variant="secondary" onClick={() => setModal("knowledge")}>知识库详情</Button><Button variant="secondary" onClick={() => setModal("rules")}>专家规则库</Button><Button variant="secondary" onClick={() => { setBasisKeyword("配电"); setModal("basis"); }}>检查依据检索</Button><Button variant="secondary" onClick={() => setModal("messages")}>待处理消息</Button></Toolbar>
    <SectionCard title="近期识别任务" eyebrow="INFERENCE QUEUE"><div className="table-wrap"><table className="data-table pi-analysis-table"><colgroup>{[250, 180, 90, 240, 120, 110].map((width, index) => <col key={index} style={{ width }} />)}</colgroup><thead><tr>{["任务", "模型", "耗时", "结果", "状态", "操作"].map((head) => <th key={head}>{head}</th>)}</tr></thead><tbody>{filtered.map((record) => <tr key={record.id}><td><span className="pi-cell" title={record.name}>{record.name}</span><small>{record.id}</small></td><td>{record.model}</td><td>{record.duration}</td><td><span className="pi-cell" title={record.output}>{record.output}</span></td><td><Pill tone={stateTone(record.status)}>{record.status}</Pill></td><td><Button variant="ghost" onClick={() => openRecord(record)}>查看详情</Button></td></tr>)}</tbody></table></div>{!filtered.length && <Empty />}</SectionCard>
    <Modal title="启动现场分析" open={modal === "analysis"} onClose={close} wide><div className="form-grid"><Field label="分析名称 *" wide><input value={analysis.name} onChange={(e) => setAnalysis({ ...analysis, name: e.target.value })} /></Field><Field label="所属项目"><select value={analysis.project} onChange={(e) => { const task = tasks.find((item) => item[3] === e.target.value); setAnalysis({ ...analysis, project: e.target.value, taskId: task?.[0] ?? "" }); }}><Options values={projectNames.slice(1)} /></select></Field><Field label="来源任务"><select value={analysis.taskId} onChange={(e) => setAnalysis({ ...analysis, taskId: e.target.value })}><option value="">独立分析</option>{tasks.filter((item) => item[3] === analysis.project).map((item) => <option value={item[0]} key={item[0]}>{item[1]}</option>)}</select></Field><Field label="处理类型"><select value={analysis.type} onChange={(e) => setAnalysis({ ...analysis, type: e.target.value })}><Options values={["图片识别", "视频关键帧", "文本分析"]} /></select></Field><Field label="分析模型"><select value={analysis.model} onChange={(e) => setAnalysis({ ...analysis, model: e.target.value })}><Options values={["消防用电视觉模型", "消防设施识别模型", "临电风险模型"]} /></select></Field><Field label="输入材料 *" wide><input value={analysis.input} placeholder="材料名称或文本描述" onChange={(e) => setAnalysis({ ...analysis, input: e.target.value })} /></Field><Field label="选择本地图片（仅在浏览器预览）" wide><input type="file" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 1_000_000) { setFormError("请选择小于 1 MB 的图片以便本地保存，或使用内置样例。"); return; } const reader = new FileReader(); reader.onload = () => { setAnalysis((item) => ({ ...item, input: file.name, image: String(reader.result) })); setFormError(""); }; reader.readAsDataURL(file); }} /></Field><Field label="现场描述 *" wide><textarea value={analysis.description} onChange={(e) => setAnalysis({ ...analysis, description: e.target.value })} /></Field></div><div className="pi-upload"><Button variant="secondary" onClick={() => { const sample = analysis.model === "消防设施识别模型" ? recordSeed[1] : analysis.model === "临电风险模型" ? recordSeed[2] : recordSeed[0]; setAnalysis({ ...analysis, input: sample.input, description: sample.description, image: sample.image }); setFormError(""); }}>使用内置现场样例</Button><p>结果按所选模型生成本地样例，需人工核查确认。</p></div>{formError && <p className="pi-error" role="alert">{formError}</p>}<Footer close={close} save={startAnalysis} saveLabel="开始分析" /></Modal>
    <Modal title="AI 处理详情" open={modal === "record"} onClose={close} wide>{selected && <div className="pi-record"><img className="pi-evidence" src={selected.image || getHazardScene(selected.output)?.src || sceneImages.electricalPanelOpen} alt={`${selected.output}现场证据`} /><Details rows={[["来源任务", `${selected.taskId} ${selected.taskName}`], ["所属项目", selected.project], ["处理时间", selected.time], ["处理类型", selected.type], ["输入内容", selected.input], ["模型结果", selected.output], ["置信度", selected.confidence], ["现场描述", selected.description], ["风险等级", <Pill tone={riskTone(selected.risk)}>{selected.risk}</Pill>], ["关联知识", documents.filter((item) => selected.basisIds.includes(item.id)).map((item) => item.title).join("、") || "尚未选择依据"], ["人工确认", selected.confirmation], ["已移交隐患", selected.hazardId || "未移交"]]} /><div className="form-grid"><Field label="人工确认结果"><select value={confirmation} onChange={(e) => setConfirmation(e.target.value)}><Options values={["建议整改", "建议专家复核", "确认无隐患"]} /></select></Field><Field label="确认意见"><input value={opinion} onChange={(e) => setOpinion(e.target.value)} placeholder="补充现场核查意见" /></Field></div>{selected.suggestionGenerated && <div className="pi-result"><h3>整改建议</h3><p>{selected.measure}</p><small>建议结合现场条件核查后执行，并保留整改与复查证据。</small></div>}<div className="detail-actions"><Button onClick={() => { patchRecord({ status: confirmation === "建议专家复核" ? "待专家复核" : "已确认", confirmation: opinion.trim() ? `${confirmation}：${opinion.trim()}` : confirmation }); notify("人工确认结果已保存"); }}>确认结果</Button><Button variant="secondary" onClick={() => { patchRecord({ suggestionGenerated: true }); notify("整改建议已生成"); }}>生成整改建议</Button><Button variant="secondary" onClick={() => { setBasisKeyword(selected.output.includes("消防") ? "消防" : selected.output.includes("临时") ? "接地" : "配电"); setModal("basis"); }}>查看关联依据</Button>{selected.confirmation.startsWith("确认无隐患") ? <Pill tone="success">已确认无隐患</Pill> : <Button variant="secondary" onClick={() => { if (selected.hazardId) { navigate?.("/hazards", selected.hazardId); return; } setRegisterDraft({ title: selected.output, risk: selected.risk, description: selected.description, measure: selected.measure }); setModal("register"); }}>{selected.hazardId ? "查看已移交隐患" : "生成隐患登记"}</Button>}</div></div>}<Footer close={close} /></Modal>
    <Modal title="检查依据检索" open={modal === "basis"} onClose={close} wide><Field label="隐患关键词"><input value={basisKeyword} onChange={(e) => setBasisKeyword(e.target.value)} placeholder="配电、消防、灭火器、接地" /></Field><div className="pi-history">{basis.map((doc) => <article className="pi-basis-card" key={doc.id}><h3>{doc.title}</h3><p>{doc.clauses}</p><small>{doc.summary}</small><Button variant="secondary" onClick={() => { setDocuments((items) => items.map((item) => item.id === doc.id ? { ...item, citations: item.citations + 1 } : item)); if (selected) patchRecord({ basisIds: Array.from(new Set([...selected.basisIds, doc.id])) }); log(doc.title, doc.category, selected ? `加入分析 ${selected.id} 的关联依据` : "中台检索引用"); notify("检查依据已引用"); }}>{selected?.basisIds.includes(doc.id) ? "再次引用" : "加入引用"} · {doc.citations}</Button></article>)}{!basis.length && <Empty text="未找到匹配依据，请更换关键词" />}</div><div className="modal-foot"><Button variant="secondary" onClick={() => setBasisKeyword("")}>重置检索</Button><Button onClick={() => setModal(selected ? "record" : null)}>{selected ? "返回处理详情" : "关闭"}</Button></div></Modal>
    <Modal title="知识库详情" open={modal === "knowledge"} onClose={close} wide><div className="pi-history">{categories.map((category) => <article className="pi-basis-card" key={category.id}><h3>{category.name}</h3><p>{category.type} · {category.scene} · 负责人：{category.owner}</p><small>{category.count.toLocaleString()} 份文档 · {category.status}</small><div className="pi-knowledge-titles">{documents.filter((item) => item.category === category.name).map((doc) => <span key={doc.id}>{doc.title}</span>)}</div></article>)}</div><div className="modal-foot"><Button variant="secondary" onClick={close}>关闭</Button>{navigate && <Button variant="secondary" onClick={() => navigate("/model-center/knowledge")}>进入知识库</Button>}<Button onClick={() => { setFormError(""); setModal("newKnowledge"); }}>新增知识</Button></div></Modal>
    <Modal title="新增知识" open={modal === "newKnowledge"} onClose={close}><div className="form-grid"><Field label="知识名称 *" wide><input value={newKnowledge.name} onChange={(e) => setNewKnowledge({ ...newKnowledge, name: e.target.value })} /></Field><Field label="知识分类"><select value={newKnowledge.category} onChange={(e) => setNewKnowledge({ ...newKnowledge, category: e.target.value })}><Options values={categories.map((item) => item.name)} /></select></Field><Field label="负责人 *"><input value={newKnowledge.owner} onChange={(e) => setNewKnowledge({ ...newKnowledge, owner: e.target.value })} /></Field><Field label="适用场景" wide><textarea value={newKnowledge.scene} onChange={(e) => setNewKnowledge({ ...newKnowledge, scene: e.target.value })} /></Field><Field label="知识内容" wide><textarea value={newKnowledge.description} onChange={(e) => setNewKnowledge({ ...newKnowledge, description: e.target.value })} /></Field></div>{formError && <p className="pi-error" role="alert">{formError}</p>}<Footer close={close} save={addKnowledge} saveLabel="保存知识" /></Modal>
    <Modal title="专家规则库" open={modal === "rules"} onClose={close} wide><div className="pi-history">{rules.map((rule) => <article className="pi-basis-card" key={rule.id}><h3>{rule.name} <Pill tone={stateTone(rule.status)}>{rule.status}</Pill></h3><p>责任组：{rule.owner}</p><small>{rule.condition}</small></article>)}</div><div className="modal-foot"><Button variant="secondary" onClick={close}>关闭</Button>{navigate && <Button variant="secondary" onClick={() => navigate("/model-center/expert-rules")}>管理规则</Button>}<Button onClick={() => { setFormError(""); setModal("newRule"); }}>新增规则</Button></div></Modal>
    <Modal title="新增规则" open={modal === "newRule"} onClose={close}><div className="form-grid"><Field label="规则名称 *" wide><input value={newRule.name} onChange={(e) => setNewRule({ ...newRule, name: e.target.value })} /></Field><Field label="责任组 *" wide><input value={newRule.owner} onChange={(e) => setNewRule({ ...newRule, owner: e.target.value })} /></Field><Field label="判定逻辑 *" wide><textarea value={newRule.condition} onChange={(e) => setNewRule({ ...newRule, condition: e.target.value })} /></Field></div>{formError && <p className="pi-error" role="alert">{formError}</p>}<Footer close={close} save={addRule} saveLabel="保存规则" /></Modal>
    <Modal title="待处理消息" open={modal === "messages"} onClose={close}><div className="pi-history">{records.filter((item) => item.status !== "已确认").map((record) => <button key={record.id} onClick={() => openRecord(record)}><span>{record.output} · {record.status}</span><small>{record.project} · {record.time}</small></button>)}{records.every((item) => item.status === "已确认") && <Empty text="当前没有待处理消息" />}</div><Footer close={close} /></Modal>
    <Modal title="生成隐患登记" open={modal === "register"} onClose={close} wide><div className="form-grid"><Field label="隐患名称 *" wide><input value={registerDraft.title} onChange={(e) => setRegisterDraft({ ...registerDraft, title: e.target.value })} /></Field><Field label="所属项目"><input value={selected?.project ?? ""} readOnly /></Field><Field label="风险等级"><select value={registerDraft.risk} onChange={(e) => setRegisterDraft({ ...registerDraft, risk: e.target.value })}><Options values={["高风险", "中风险", "低风险"]} /></select></Field><Field label="问题描述 *" wide><textarea value={registerDraft.description} onChange={(e) => setRegisterDraft({ ...registerDraft, description: e.target.value })} /></Field><Field label="建议整改措施 *" wide><textarea value={registerDraft.measure} onChange={(e) => setRegisterDraft({ ...registerDraft, measure: e.target.value })} /></Field></div><p className="pi-note">提交后携带证据、来源任务和发现时间进入隐患登记，继续补充责任单位及整改期限。</p>{formError && <p className="pi-error" role="alert">{formError}</p>}<Footer close={close} save={register} saveLabel="移交隐患登记" /></Modal>
  </div>;
}
